// Generates supabase/seed.sql from lib/catalog-data.ts.  Run: npm run gen:seed
import { writeFileSync } from "node:fs";
import { CATALOG } from "../lib/catalog-data";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const arr = (xs: (string | number)[], type: string) =>
  `array[${xs.map((x) => (typeof x === "number" ? x : q(x))).join(",")}]::${type}[]`;

const rows = CATALOG.map(
  (d) =>
    `  (${[
      q(d.id),
      q(d.name),
      q(d.country),
      q(d.state),
      arr(d.types, "text"),
      d.costMin,
      d.costMax,
      arr(d.bestMonths, "smallint"),
      `${q(JSON.stringify(d.travel))}::jsonb`,
      d.hasTreks,
      q(d.blurb),
    ].join(", ")})`,
);

const sql = `-- Destination catalog seed (${CATALOG.length} destinations).
-- Generated by scripts/gen-seed.ts from lib/catalog-data.ts. Safe to re-run.
insert into public.destinations (id, name, country, state, types, cost_min, cost_max, best_months, travel, has_treks, blurb) values
${rows.join(",\n")}
on conflict (id) do update set
  name = excluded.name, country = excluded.country, state = excluded.state, types = excluded.types,
  cost_min = excluded.cost_min, cost_max = excluded.cost_max,
  best_months = excluded.best_months, travel = excluded.travel,
  has_treks = excluded.has_treks, blurb = excluded.blurb;
`;
writeFileSync("supabase/seed.sql", sql);
console.log(`Wrote supabase/seed.sql (${CATALOG.length} destinations)`);
